
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


/**** BEGIN PROCEDURE _operating_system ****/

static CLUREF STR_UNIX;
static int _operating_system_own_init = 0;

errcode
_operating_system(CLUREF *ret_1)
{
    errcode err;
    if (_operating_system_own_init == 0) {
        stringOPcons("UNIX", CLU_1, CLUREF_make_num(4), &STR_UNIX);
        _operating_system_own_init = 1;
    }
    enter_proc(2);

  LINE(3);
    {
    {
    ret_1->str = STR_UNIX.str;
    }
    {signal (ERR_ok);}}

    goto end_0;
  ex_0:
    if (err != ERR_failure)
        elist[0] = _pclu_erstr(err);
    signal(ERR_failure);
  end_0:
    elist[0] = no_return_values_STRING;
    signal(ERR_failure);
}

/**** END PROCEDURE _operating_system ****/



/**** BEGIN PROCEDURE _host_system ****/

extern errcode _host_name();

errcode
_host_system(CLUREF *ret_1)
{
    errcode err;
    enter_proc(6);

  LINE(7);
    {
    {
    CLUREF T_1_1;
    err = _host_name(&T_1_1);
    if (err != ERR_ok) goto ex_0;
    ret_1->num = T_1_1.num;
    }
    {signal (ERR_ok);}}

    goto end_0;
  ex_0:
    if (err != ERR_failure)
        elist[0] = _pclu_erstr(err);
    signal(ERR_failure);
  end_0:
    elist[0] = no_return_values_STRING;
    signal(ERR_failure);
}

/**** END PROCEDURE _host_system ****/

