#!/bin/sh

# let the compiler be set in the environment
cc=${CLUCC-${CC-cc}}

verbose=
opt=
lflags=
libpclu=-lpclu_opt

usage() {
    cat 1>&2 <<'//GO.SYSIN DD *'
Usage: plink [-v] [-opt|-debug] [--] linker args ...
//GO.SYSIN DD *
    exit 2
}


if [ $# = 0 ]; then
    usage
fi

while [ $# != 0 ];
do
    case "$1" in
	-debug|--debug)
	    if [ "$opt" ] && [ "$opt" != "debug" ]; then
		echo "$1": conflicts with preceding options 1>&2
		usage
	    fi
	    lflags=-no-pie
	    libpclu=-lpclu_debug
	    opt=debug
	    ;;

	-opt|--opt)
	    if [ "$opt" ] && [ "$opt" != "opt" ]; then
		echo "$1": conflicts with preceding options 1>&2
		usage
	    fi
	    libpclu=-lpclu_opt
	    opt=opt
	    ;;

	-v|-verbose|--verbose)
	    verbose=y
	    ;;

	--) # pass the remaining args to cc/ld
	    shift
	    break
	    ;;

	-*) # unknown option - pass it and the remaining args to cc/ld
	    break
	    ;;

	*)  # non-option - pass it and the remaining args to cc/ld
	    break
	    ;;
    esac

    if [ $# -ge 1 ]; then shift; fi
done

if [ "$verbose" ]; then
    PS4=''			# suppress '+' prefix from set -x
    set -x
fi
$cc $lflags "$@" -L"${CLUHOME}"/code $libpclu -lm -lgc
