#!/bin/sh

# let the compiler be set in the environment
cc=${CLUCC-${CC-cc}}

output=a.out
files=
verbose=
opt=
lflag=-lpclu_opt

usage="Usage: plink <object file> ... <Option>*\n\
Options: -debug, -opt, -o outputfile, -v"

if [ $# = 0 ]; then
    echo $usage
    exit 2
fi

while [ $# != 0 ];
do
    case "$1" in
	-debug)
	    lflag=-lpclu_debug
	    ;;

	-opt)
	    lflag=-lpclu_opt
	    ;;

	-o*)
	    output=`echo "$1" | sed 's/^-o//'`
	    test -n "$output"
	    if [ $? != 0 ]; then
		shift || exit 2
		output=$1
	    fi
	    ;;

	-v*)
	    verbose=y
	    ;;

	-*)
	    echo $usage
	    exit 2
	    ;;

	*)
	    files="$files $1"
	    ;;
    esac

    if [ $# -ge 1 ]; then shift; fi
done

if [ "$verbose" ]; then
    PS4=''			# suppress '+' prefix from set -x
    set -x
fi
$cc -o $output $files -L$CLUHOME/code $lflag -lm -lgc
