#!/bin/sh

# let the compiler be set in the environment
cc=${CLUCC-${CC-cc}}

output=a.out
files=
verbose=
opt=
lflag=-lpclu_opt

usage() {
    cat 1>&2 <<'//GO.SYSIN DD *'
Usage: plink [-o output] [-opt|-debug] [-v] objfile ...
//GO.SYSIN DD *
    exit 2
}


if [ $# = 0 ]; then
    usage
fi

while [ $# != 0 ];
do
    case "$1" in
	-debug)
	    lflag=-lpclu_debug
	    ;;

	-opt)
	    lflag=-lpclu_opt
	    ;;

	-o)
	    shift
	    output="$1"
	    if [ -z "$output" ]; then
		usage
	    fi
	    ;;

	-v*)
	    verbose=y
	    ;;

	-*)
	    echo unknown option "$1" 1>&2
	    usage
	    ;;

	*)
	    files="$files $1"
	    ;;
    esac

    if [ $# -ge 1 ]; then shift; fi
done

if [ "$verbose" ]; then
    PS4=''			# suppress '+' prefix from set -x
    set -x
fi
$cc -o $output $files -L$CLUHOME/code $lflag -lm -lgc
